debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.son.project_a: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/travel # jdbc url ??(in-memory db ??)
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver #h2 ???? ??
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true #sql?? ????
    properties:
      hibernate:
        format_sql: true #sql ??? ??
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

jwt:
  secret: "cXdlcnR5dWlvcGFzZGZnaGprbHp4Y3Zibm0senhjdmJubWRmZ2hqa2x3ZXJ0eXVp"